#!/usr/bin/env bash
# =============================================================================
# generate-tfvars.sh
# Auto-generates web-gui/infrastructure/terraform.tfvars from the dev stack
# outputs. Run this ONCE before doing terraform apply in web-gui/infrastructure.
#
# Usage:
#   cd /Users/suresh/Documents/api-gateway-terraform
#   bash web-gui/infrastructure/generate-tfvars.sh
# =============================================================================
set -euo pipefail

DEV_DIR="environments/dev"
GUI_DIR="web-gui/infrastructure"
TFVARS="$GUI_DIR/terraform.tfvars"
REGION="eu-north-1"

echo "📋 Reading outputs from $DEV_DIR ..."

LAMBDA_FUNCTION_NAME=$(terraform -chdir="$DEV_DIR" output -raw lambda_function_name)
COGNITO_POOL_ID=$(terraform -chdir="$DEV_DIR" output -raw cognito_user_pool_id)
COGNITO_CLIENT_ID=$(terraform -chdir="$DEV_DIR" output -raw cognito_client_id)

# Get the authorizer function name from Terraform state
# (falls back to conventional naming if output not yet available)
AUTHORIZER_FUNCTION_NAME=$(terraform -chdir="$DEV_DIR" output -raw authorizer_function_name 2>/dev/null \
  || echo "${LAMBDA_FUNCTION_NAME%-lambda}-lambda-authorizer")

echo "✅ Lambda function name : $LAMBDA_FUNCTION_NAME"
echo "✅ Cognito pool ID      : $COGNITO_POOL_ID"
echo "✅ Cognito client ID    : $COGNITO_CLIENT_ID"
echo "✅ Authorizer fn name   : $AUTHORIZER_FUNCTION_NAME"

ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text --region "$REGION")

# Store PLAIN Lambda ARNs (no API GW invoke wrapper, no :live qualifier).
# The provisioner code (buildIntegrationUri / buildAuthorizerUri) converts these
# to the correct API GW invoke ARN format at runtime, stripping any qualifier.
# Keeping plain ARNs here avoids the bug where :live is baked into the invoke URI.
LAMBDA_ARN="arn:aws:lambda:${REGION}:${ACCOUNT_ID}:function:${LAMBDA_FUNCTION_NAME}"
AUTHORIZER_ARN="arn:aws:lambda:${REGION}:${ACCOUNT_ID}:function:${AUTHORIZER_FUNCTION_NAME}"

echo "✅ Lambda ARN           : $LAMBDA_ARN"
echo "✅ Authorizer ARN       : $AUTHORIZER_ARN"

cat > "$TFVARS" <<EOF
# Auto-generated by generate-tfvars.sh on $(date)
# DO NOT hand-edit — re-run generate-tfvars.sh to regenerate.
#
# existing_lambda_arn / existing_authorizer_lambda_arn are PLAIN Lambda ARNs.
# The provisioner converts them to API GW invoke ARN format at runtime.

aws_region    = "$REGION"
project_name  = "api-portal"
environment   = "dev"

# Lambda backend (plain ARN — provisioner wraps to invoke ARN format)
existing_lambda_arn           = "$LAMBDA_ARN"
existing_lambda_function_name = "$LAMBDA_FUNCTION_NAME"

# Cognito (JWT auth)
existing_cognito_pool_id   = "$COGNITO_POOL_ID"
existing_cognito_client_id = "$COGNITO_CLIENT_ID"

# Custom authorizer Lambda (plain ARN — provisioner wraps to invoke ARN format)
existing_authorizer_lambda_arn    = "$AUTHORIZER_ARN"
existing_authorizer_function_name = "$AUTHORIZER_FUNCTION_NAME"

existing_aws_region = "$REGION"
log_retention_days  = 14
cors_allowed_origin = "*"
EOF

echo ""
echo "✅  Written to $TFVARS"
echo ""
echo "Next steps:"
echo "  1. Review $TFVARS"
echo "  2. terraform -chdir=$GUI_DIR init   # only if first time"
echo "  3. terraform -chdir=$GUI_DIR apply"

