#!/usr/bin/env bash
# =============================================================================
# generate-tfvars.sh
# Auto-generates web-gui/infrastructure/terraform.tfvars from the dev stack
# outputs. Run this ONCE before doing terraform apply in web-gui/infrastructure.
#
# Usage:
#   cd /Users/suresh/Documents/api-gateway-terraform
#   bash web-gui/infrastructure/generate-tfvars.sh
# =============================================================================
set -euo pipefail

DEV_DIR="environments/dev"
GUI_DIR="web-gui/infrastructure"
TFVARS="$GUI_DIR/terraform.tfvars"
REGION="eu-north-1"

echo "📋 Reading outputs from $DEV_DIR ..."

LAMBDA_FUNCTION_NAME=$(terraform -chdir="$DEV_DIR" output -raw lambda_function_name)
COGNITO_POOL_ID=$(terraform -chdir="$DEV_DIR" output -raw cognito_user_pool_id)
COGNITO_CLIENT_ID=$(terraform -chdir="$DEV_DIR" output -raw cognito_client_id)

# Get the authorizer function name from Terraform state
# (falls back to conventional naming if output not yet available)
AUTHORIZER_FUNCTION_NAME=$(terraform -chdir="$DEV_DIR" output -raw authorizer_function_name 2>/dev/null \
  || echo "${LAMBDA_FUNCTION_NAME%-lambda}-lambda-authorizer")

echo "✅ Lambda function name : $LAMBDA_FUNCTION_NAME"
echo "✅ Cognito pool ID      : $COGNITO_POOL_ID"
echo "✅ Cognito client ID    : $COGNITO_CLIENT_ID"
echo "✅ Authorizer fn name   : $AUTHORIZER_FUNCTION_NAME"

# Build the correct API GW invoke ARN format required by CreateIntegrationCommand
# and CreateAuthorizerCommand in API Gateway v2:
#   arn:aws:apigateway:{region}:lambda:path/2015-03-31/functions/{lambda-arn}/invocations
ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text --region "$REGION")
LAMBDA_ARN="arn:aws:lambda:${REGION}:${ACCOUNT_ID}:function:${LAMBDA_FUNCTION_NAME}:live"
AUTHORIZER_ARN="arn:aws:lambda:${REGION}:${ACCOUNT_ID}:function:${AUTHORIZER_FUNCTION_NAME}"

LAMBDA_INVOKE_ARN="arn:aws:apigateway:${REGION}:lambda:path/2015-03-31/functions/${LAMBDA_ARN}/invocations"
AUTHORIZER_INVOKE_ARN="arn:aws:apigateway:${REGION}:lambda:path/2015-03-31/functions/${AUTHORIZER_ARN}/invocations"

echo "✅ Lambda invoke ARN    : $LAMBDA_INVOKE_ARN"
echo "✅ Authorizer invoke ARN: $AUTHORIZER_INVOKE_ARN"

cat > "$TFVARS" <<EOF
# Auto-generated by generate-tfvars.sh on $(date)
# DO NOT hand-edit the *_arn values — they must be in API GW invoke ARN format.

aws_region    = "$REGION"
project_name  = "api-portal"
environment   = "dev"

# Lambda backend
existing_lambda_arn           = "$LAMBDA_INVOKE_ARN"
existing_lambda_function_name = "$LAMBDA_FUNCTION_NAME"

# Cognito (JWT auth)
existing_cognito_pool_id   = "$COGNITO_POOL_ID"
existing_cognito_client_id = "$COGNITO_CLIENT_ID"

# Custom authorizer Lambda (X-Api-Key auth)
existing_authorizer_lambda_arn    = "$AUTHORIZER_INVOKE_ARN"
existing_authorizer_function_name = "$AUTHORIZER_FUNCTION_NAME"

existing_aws_region = "$REGION"
log_retention_days  = 14
cors_allowed_origin = "*"
EOF

echo ""
echo "✅  Written to $TFVARS"
echo ""
echo "Next steps:"
echo "  1. Review $TFVARS"
echo "  2. terraform -chdir=$GUI_DIR init   # only if first time"
echo "  3. terraform -chdir=$GUI_DIR apply"

